export const refs = {
  // preLoader
  // header
  navLogo: document.querySelector('.navigation__logo'),
  navPage: document.querySelector('.navigation__page'),
  searchWrap: document.querySelector('.search-wrap'),
  libWrap: document.querySelector('.library-button__container'),
  navPageHome: document.querySelector('.navigation__page-home'),
  navPageLib: document.querySelector('.navigation__page-library'),
  header: document.querySelector('header'),
  addToWachedBtn: document.querySelector('[data-click="addToWached"]'),
  logoText: document.querySelector('.logo-name'),
  // search
  // myLibrary
  // interface
  // genere
  // movie
  movieGallery: document.querySelector('.movie-gallery'),
  // footer
  goItStud: document.querySelector('.goItStud-js'),
  // modalMovie
  closeModalBtn: document.querySelector('.modal-close-btn'),
  modalBackdrop: document.querySelector('.backdrop'),
  watchedBtn: document.querySelector('.button-watched'),
  queueBtn: document.querySelector('.button-queue'),
  // modalTeam
  closeModalBtn: document.querySelector('.modal-close-btn'),
  modalBackdrop: document.querySelector('.backdrop'),
  // modalMovie
  openMovieModal: document.querySelector('[data-movie-modal-open]'),
  closeMovieModalBtn: document.querySelector('[data-movie-modal-close]'),
  movieModalBackdrop: document.querySelector('[data-movie-modal-backdrop]'),
  movieModal: document.querySelector('[data-movie-modal]'),
  // modalActors
  openActorsModalBtn: document.querySelector('[data-actors-modal-open]'),
  closeActorsModalBtn: document.querySelector('[data-actors-modal-close]'),
  actorsModalBackdrop: document.querySelector('[data-actors-modal-backdrop]'),
  actorsModal: document.querySelector('[data-actors-modal]'),
  //login
  signInBtn: document.querySelector('[data-signin-open]'),
  signInCloseBtn: document.querySelector('[data-modal-close-form]'),
  backdropSignIn: document.querySelector('[data-modal-signin]'),
  signUpLink: document.querySelector('[data-modal-link]'),
  backdropSignUp: document.querySelector('[data-modal-signup]'),
  signUpCloseBtn: document.querySelector('[data-modal-signup-close]'),
  signInLink: document.querySelector('[data-modal-link-signin]'),
  inputPassword: document.querySelector('[data-password]'),
  inputPasswordRepeat: document.querySelector('[data-password-repeat]'),
  formSignUp: document.querySelector('[data-signup]'),
  passwordNotMatchAlert: document.querySelector('[data-not-match]'),
};
