export const refs = {
  //html
  html: document.querySelector('html'),
  // footer
  goItStud: document.querySelector('.goItStud-js'),
  toggleTheme: document.querySelector('#toggle-theme'),
  //change language
  changeLanguage: document.querySelector('#toggle-language'),
  modalTeamLanguage: document.querySelector('.box-team-js'),
  // preLoader
  // header
  navLogo: document.querySelector('.navigation__logo'),
  navPage: document.querySelector('.navigation__page'),
  searchWrap: document.querySelector('.search-wrap'),
  libWrap: document.querySelector('.library-button__container'),
  navPageHome: document.querySelector('.navigation__page-home'),
  navPageLib: document.querySelector('.navigation__page-library'),
  header: document.querySelector('header'),
  addToWachedBtn: document.querySelector('[data-click="addToWached"]'),
  logoText: document.querySelector('.logo-name'),
  queueButton: document.querySelector('.library-button__queue'),
  watchedButton: document.querySelector('.library-button__watched'),
  // search
  // myLibrary
  loadWathedBtn: document.querySelector('.library-button__watched'),
  loadQueueBtn: document.querySelector('.library-button__queue'),
  // interface
  // genere
  // movie
  movieGallery: document.querySelector('.movie-gallery'),
  // modalMovie
  closeModalBtn: document.querySelector('.modal-close-btn'),
  modalBackdrop: document.querySelector('.backdrop'),
  watchedBtn: document.querySelector('.button-watched'),
  queueBtn: document.querySelector('.button-queue'),
  // modalTeam
  closeModalBtn: document.querySelector('.modal-close-btn'),
  modalBackdrop: document.querySelector('.backdrop'),
  // modalMovie
  openMovieModal: document.querySelector('[data-movie-modal-open]'),
  closeMovieModalBtn: document.querySelector('[data-movie-modal-close]'),
  movieModalBackdrop: document.querySelector('[data-movie-modal-backdrop]'),
  movieModal: document.querySelector('[data-movie-modal]'),
  // modalActors
  openActorsModalBtn: document.querySelector('[data-actors-modal-open]'),
  closeActorsModalBtn: document.querySelector('[data-actors-modal-close]'),
  actorsModalBackdrop: document.querySelector('[data-actors-modal-backdrop]'),
  actorsModal: document.querySelector('[data-actors-modal]'),
  //login
  signInBtn: document.querySelector('[data-signin-open]'),
  btnLoginWrap: document.querySelector('[data-btn-login-wrap]'),
  signInCloseBtn: document.querySelector('[data-modal-close-form]'),
  backdropSignIn: document.querySelector('[data-modal-signin]'),
  signUpLink: document.querySelector('[data-modal-link]'),
  backdropSignUp: document.querySelector('[data-modal-signup]'),
  signUpCloseBtn: document.querySelector('[data-modal-signup-close]'),
  signInLink: document.querySelector('[data-modal-link-signin]'),
  inputPassword: document.querySelector('[data-password]'),
  inputPasswordRepeat: document.querySelector('[data-password-repeat]'),
  formSignUp: document.querySelector('[data-signup]'),
  passwordNotMatchAlert: document.querySelector('[data-not-match]'),
  modalBtnTosignIn: document.queryCommandValue('[data-modalbtn-tosignin]'),
  //pagination
  paginationList: document.querySelector('[data-pagination]'),
  accountCreatedText: document.querySelector('[data-acc-already-created]'),
  btnValueOut: document.querySelector('[data-btn-value-out]'),
  signInForm: document.querySelector('[data-signIn-form]'),
  signInErrorText: document.querySelector('[data-signin-errorText]'),
};
