// import './js/API/api';
import './js/header';
import './js/movies';
import './js/addToWatched';
import './js/modalTeam';
import './js/api-storage';
import './js/genre';
import './js/modalTeam';
import './js/login';
import './js/modalMovie';
import './js/modalActors';
import './js/changeColorTheme';
import './js/pagination/pagination';
import './js/pagination/pagination-api';
import './js/translation/fnTranslation';
import './js/myLibrary';
