// import './js/API/api';
import './js/header';
import './js/movies';
import './js/addToWatched';
import './js/modalTeam';
import './js/api-storage';
import './js/genre';
import './js/modalTeam';
import './js/login';
import './js/modalMovie';
import './js/modalActors';
import './js/changeColorTheme';
import './js/API/auth';
